import { NextRequest, NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { writeFile, readFile } from "fs/promises";
import { existsSync } from "fs";
import path from "path";
import crypto from "crypto";

function generateSecret(len = 32): string {
  return crypto.randomBytes(len).toString("base64").slice(0, len);
}

async function writeEnvLocal(vars: Record<string, string>) {
  const envPath = path.join(process.cwd(), ".env.local");

  // Read existing content if file exists
  let existing: Record<string, string> = {};
  if (existsSync(envPath)) {
    const content = await readFile(envPath, "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      existing[key] = val;
    }
  }

  // Merge new vars
  const merged = { ...existing, ...vars };

  // Build file content
  const lines = [
    "# Auto-generated by setup wizard",
    `# Generated: ${new Date().toISOString()}`,
    "",
    "# Database",
    `MONGODB_URI=${merged.MONGODB_URI ?? ""}`,
    "",
    "# NextAuth",
    `NEXTAUTH_SECRET=${merged.NEXTAUTH_SECRET ?? generateSecret()}`,
    `NEXTAUTH_URL=${merged.NEXTAUTH_URL ?? "http://localhost:3000"}`,
    "",
    "# App",
    `NEXT_PUBLIC_APP_URL=${merged.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000"}`,
    `SETUP_COMPLETE=${merged.SETUP_COMPLETE ?? "true"}`,
    "",
    "# Payment — Instamojo",
    `INSTAMOJO_API_KEY=${merged.INSTAMOJO_API_KEY ?? ""}`,
    `INSTAMOJO_AUTH_TOKEN=${merged.INSTAMOJO_AUTH_TOKEN ?? ""}`,
    `INSTAMOJO_SALT=${merged.INSTAMOJO_SALT ?? ""}`,
    "",
    "# Payment — Cashfree",
    `CASHFREE_APP_ID=${merged.CASHFREE_APP_ID ?? ""}`,
    `CASHFREE_SECRET_KEY=${merged.CASHFREE_SECRET_KEY ?? ""}`,
    "",
    "# Email (Gmail SMTP)",
    `GMAIL_USER=${merged.GMAIL_USER ?? ""}`,
    `GMAIL_APP_PASSWORD=${merged.GMAIL_APP_PASSWORD ?? ""}`,
    "",
    "# WhatsApp (Twilio)",
    `TWILIO_ACCOUNT_SID=${merged.TWILIO_ACCOUNT_SID ?? ""}`,
    `TWILIO_AUTH_TOKEN=${merged.TWILIO_AUTH_TOKEN ?? ""}`,
    `TWILIO_WHATSAPP_FROM=${merged.TWILIO_WHATSAPP_FROM ?? ""}`,
    "",
    "# Licence",
    `LICENCE_KEY=${merged.LICENCE_KEY ?? ""}`,
  ];

  await writeFile(envPath, lines.join("\n"), "utf-8");
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { site, admin, database, notifications, licence } = body;

    if (!site?.siteName || !admin?.email || !admin?.password || !database?.uri) {
      return NextResponse.json(
        { success: false, data: null, message: "All required fields must be filled" },
        { status: 400 }
      );
    }

    if (admin.password.length < 8) {
      return NextResponse.json(
        { success: false, data: null, message: "Password must be at least 8 characters" },
        { status: 400 }
      );
    }

    // Connect to the provided database
    const mongoose = await import("mongoose");
    if (mongoose.default.connection.readyState !== 0) {
      await mongoose.default.disconnect();
    }

    try {
      await mongoose.default.connect(database.uri, {
        bufferCommands: false,
        serverSelectionTimeoutMS: 8000,
      });
    } catch (err) {
      return NextResponse.json(
        { success: false, data: null, message: `Database connection failed: ${(err as Error).message}` },
        { status: 400 }
      );
    }

    const { default: Settings } = await import("@/models/Settings");
    const { default: User } = await import("@/models/User");

    // Create or update admin user
    const existingAdmin = await User.findOne({ email: admin.email.toLowerCase() });
    if (!existingAdmin) {
      const hashed = await bcrypt.hash(admin.password, 12);
      await User.create({
        name: admin.name || "Admin",
        email: admin.email.toLowerCase().trim(),
        password: hashed,
        role: "admin",
      });
    } else {
      const hashed = await bcrypt.hash(admin.password, 12);
      await User.updateOne(
        { email: admin.email.toLowerCase() },
        { role: "admin", password: hashed, name: admin.name || existingAdmin.name }
      );
    }

    // Save settings to DB
    await Settings.findOneAndUpdate(
      {},
      {
        $set: {
          siteName: site.siteName,
          contactEmail: site.contactEmail || admin.email,
          setupComplete: true,
        },
      },
      { upsert: true }
    );

    // Write .env.local
    const nextAuthSecret = generateSecret(48);
    await writeEnvLocal({
      MONGODB_URI: database.uri,
      NEXTAUTH_SECRET: nextAuthSecret,
      NEXTAUTH_URL: site.appUrl || "http://localhost:3000",
      NEXT_PUBLIC_APP_URL: site.appUrl || "http://localhost:3000",
      SETUP_COMPLETE: "true",
      GMAIL_USER: notifications?.gmailUser || "",
      GMAIL_APP_PASSWORD: notifications?.gmailAppPassword || "",
      TWILIO_ACCOUNT_SID: notifications?.twilioSid || "",
      TWILIO_AUTH_TOKEN: notifications?.twilioToken || "",
      TWILIO_WHATSAPP_FROM: notifications?.twilioWhatsapp || "",
      LICENCE_KEY: licence?.key || "",
    });

    return NextResponse.json({
      success: true,
      data: { adminEmail: admin.email },
      message: "Setup complete! .env.local has been written. Please restart the server.",
    });
  } catch (error) {
    console.error("Setup error:", error);
    return NextResponse.json(
      { success: false, data: null, message: `Setup failed: ${(error as Error).message}` },
      { status: 500 }
    );
  }
}
